---
- name: Install Pass
  tags: pass
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
    - name: Install Pass with a package manager
      ansible.builtin.package:
        name:
        - pass
        state: latest
...
