bash_default_dir: "{{ ansible_env.HOME }}"
bash_paths_darwin:
  - "/opt/homebrew/bin"
  - "/opt/homebrew/sbin"
  - "/Users/michal/Library/Python/3.9/bin"
inputrc_default_dir: "{{ ansible_env.HOME }}"
