#!/bin/sh

pydoc="pydoc3"

! command -v "$pydoc" > "/dev/null" && echo "$pydoc not found on the \$PATH"

if [ "$#" -gt 0 ]; then
	$pydoc "$1" && exit 0
else
	while read -r line; do
		for arg in $line; do
			case "$arg" in
				import)
					;;
				from)
					;;
				*)
					$pydoc "$arg"
					break
					;;
			esac
		done
	done < "/dev/stdin"
fi
