#!/bin/sh

###################################################
#                || DISCLAIMER ||                 #
#  This multicommand script works on hard links.  #
#  The path of the execution relies on the name   #
#               of the executable.                #
###################################################

test -z $EDITOR && echo '$EDITOR was not exported' && exit 1
test -z $JOURNAL && echo '$JOURNAL was not exported' && exit 1

create_entry () {
	read -p "Enter a name: " name
	test -z $name && echo 'name cannot be empty' && exit 1
	d=$(date "+%Y%m%d%H%M%S")
	dir="$JOURNAL/zettel"
	mkdir -p "$dir"
	touch "$dir/$d-$name"
	$EDITOR "$_"
}

test ${0##*/} = zettelp && \
	find "$JOURNAL"/zettel -maxdepth 2 -type f | grep "${1:-""}" && exit 0

test ${0##*/} = zettelf && \
	find "$JOURNAL"/zettel -maxdepth 2 -type f | fzf | xargs -I {} $EDITOR "{}" \
	&& exit 0

test ${0##*/} = zettel && create_entry
