---
- name: Install Kind
  tags:
  - kind
  block:
  - name: Get Kind released binary to the destination directory
    become: true
    ansible.builtin.get_url:
      url: "{{ kind_release_source_url }}"
      dest: "{{ kind_binary_dest_dir }}/kind"
      mode: u=+rwx,g=+rx-x,o=+rx-w
...
