---
- name: Install Neovim
  tags: neovim
  become_user: "{{ user }}"
  block:
    - name: Install Neovim on MacOS with Homebrew
      import_tasks: macos.yaml
      when: ansible_distribution == "MacOSX"

    - name: Confirm that Git available
      command: git version
      register: git_exists
      check_mode: false
      changed_when: false
      failed_when: git_exists.rc != 0

    - name: Ensure Pyenv is available
      command: pyenv version
      register: pyenv_exists
      check_mode: false
      changed_when: false
      failed_when: pyenv_exists.rc != 0

    - name: Ensure dedicated Python virtual environment is created with Pyenv
      command: pyenv virtualenv neovim
      check_mode: false
      changed_when: false
      ignore_errors: true
      when: pyenv_exists.rc == 0

    - name: Register the path to the Pyenv rot directory
      command: pyenv root
      register: pyenv_root
      check_mode: false
      changed_when: false
      when: pyenv_exists.rc == 0

    - name: >-
        Register the path to the Python interpreter from the virtual environment
        created with Pyenv
      set_fact:
        pyenv_neovim_env_exec: "{{ pyenv_root.stdout }}/versions/neovim/bin/python3"
      when: pyenv_exists.rc == 0

    - name: >-
        Make sure that pynvim Python package is installed in the provided
        virtual environment
      command: "{{ pyenv_neovim_env_exec }} -m pip install pynvim"
      register: pynvim_install_result
      check_mode: false
      changed_when: false
      failed_when: pynvim_install_result.rc != 0

    # - name: Use the LTS version of Node.js with Nvm
    #   command: source {{ home }}/.bashrc && nvm use --lts
    #   register: nvm_use_cmd_result
    #   check_mode: false
    #   changed_when: false
    #   failed_when: nvm_use_cmd_result.rc != 0

    - name: Confirm that Node is available
      shell: >-
        bash -ilc 'source {{home }}/.bashrc &&
        nvm use --lts &&
        node --version'
      register: node_exists
      check_mode: false
      changed_when: false
      failed_when: node_exists.rc != 0

    # - name: Ensure Neovim configuration directory is present

    # - name: Ensure Neovim configuration file is available

    # - name: Make sure the plugin directory is present

    # - name: Install Neovim plugins

    # - name: Install required LSP servers

    # - name: Make sure Ripgrep is installed

    # - name: Make sure Fd is installed

...
