---
- name: Install Neovim
  tags: neovim
  become_user: "{{ user }}"
  block:
    - name: Install Neovim on MacOS with Homebrew
      import_tasks: macos.yaml
      when: ansible_distribution == "MacOSX"

    - name: Confirm that Git is available
      command: git version
      register: git_exists
      check_mode: false
      changed_when: false
      failed_when: git_exists.rc != 0

    - name: Ensure that Pyenv is available
      command: pyenv --version
      register: pyenv_exists
      check_mode: false
      changed_when: false
      failed_when: pyenv_exists.rc != 0

    - name: Ensure the dedicated Python virtual environment is created with Pyenv
      command: pyenv virtualenv neovim
      check_mode: false
      changed_when: false
      ignore_errors: true
      when: pyenv_exists.rc == 0

    - name: Register the path to the Pyenv root directory
      command: pyenv root
      register: pyenv_root
      check_mode: false
      changed_when: false
      when: pyenv_exists.rc == 0

    - name: >-
        Register the path to the Python interpreter from the virtual environment
        created with Pyenv
      set_fact:
        pyenv_neovim_env_exec: "{{ pyenv_root.stdout }}/versions/neovim/bin/python3"
      when: pyenv_exists.rc == 0

    - name: >-
        Make sure that pynvim Python package is installed in the provided
        virtual environment
      command: "{{ pyenv_neovim_env_exec }} -m pip install pynvim"
      register: pynvim_install_result
      check_mode: false
      changed_when: false
      failed_when: pynvim_install_result.rc != 0

    - name: Confirm that Node is available
      command: node --version
      register: node_exists
      check_mode: false
      changed_when: false
      failed_when: node_exists.rc != 0

    - name: Confirm that Npm is available
      command: npm --version
      register: npm_exists
      check_mode: false
      changed_when: false
      failed_when: npm_exists.rc != 0

    - name: Ensure that Neovim configuration directory is present
      file:
        path: "{{ neovim_config_dir }}"
        state: directory
        mode: u=+rwx,g=+r-wx,o=+r-wx

    - name: Ensure Neovim configuration files are present
      copy:
        src: files/
        dest: "{{ neovim_config_dir }}/"
        mode: u=+rw,g=+r-wx,o=+r-wx

    - name: Install/update Neovim plugins (Lazy installation seems to be blocking)
      command: nvim --headless +qall
      register: nvim_plugins_install_result
      check_mode: false
      changed_when: false
      failed_when: nvim_plugins_install_result.rc != 0

    - name: Make sure Ripgrep is installed
      command: rg --version
      register: rg_exists
      check_mode: false
      changed_when: false
      failed_when: rg_exists.rc != 0

    - name: Make sure Fd is installed
      command: fd --version
      register: fd_exists
      check_mode: false
      changed_when: false
      failed_when: fd_exists.rc != 0

    - name: Ensure that Tree-sitter is installed
      command: tree-sitter --version
      register: tree_sitter_exists
      check_mode: false
      changed_when: false
      failed_when: tree_sitter_exists.rc != 0

    - name: Make sure that Neovim Tree-sitter is installed and updated
      command: nvim --headless '+TSInstallSync all' +qa
      register: tree_sitter_install_result
      check_mode: false
      changed_when: false
      failed_when: tree_sitter_install_result.rc != 0

    - name: Ensure that Go is installed and available
      command: go version
      register: go_exists
      check_mode: false
      changed_when: false
      failed_when: go_exists.rc != 0

    - name: Install Gopls language server for the Go programming language
      command: go install golang.org/x/tools/gopls@latest
      register: gopls_install_result
      check_mode: false
      changed_when: false
      failed_when: gopls_install_result.rc != 0

    - name: Install Pyright language server for Python with Npm
      command: npm install -g pyright
      register: pyright_install_result
      check_mode: false
      changed_when: false
      failed_when: pyright_install_result.rc != 0

    - name: Install HTML language server with Npm
      command: npm install -g vscode-langservers-extracted
      register: html_lsp_install_result
      check_mode: false
      changed_when: false
      failed_when: html_lsp_install_result.rc != 0
...
