---
- name: Install Bash
  tags: bash
  become_user: "{{ user }}"
  block:
    - name: Install recent Bash version on MacOS
      include_tasks: macos.yaml
      when: ansible_distribution == "MacOSX"

    - name: Check if Pyenv is installed
      shell: "command -v pyenv"
      register: pyenv_exists

    - name: Ensure Bash configuration file is present
      template:
        src: templates/bashrc.j2
        dest: "{{ bash_default_dir }}/.bashrc"
        mode: u=+rwx,g=+r-wx,o=+r-wx

    - name: Ensure Bash profile file is present
      copy:
        src: files/profile
        dest: "{{ bash_default_dir }}/.profile"
        mode: u=+rwx,g=+r-wx,o=+r-wx
...
