---
- name: Install Tree
  tags:
  - tree
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Tree with a package manager
    ansible.builtin.package:
      name:
      - tree
      state: latest
...
