user: "$USER"
home: "$HOME"
neovim_config_dir: "{{ home }}/.config/nvim"
neovim_plugins:
  - name: "github/copilot.vim"
    comment: "GitHub Copilot"
  - name: "tommcdo/vim-exchange"
    comment: "Swap words, lines and paragraphs"
  - name: "tweekmonster/gofmt.vim"
    comment: "Format Go code on save"
  - name: "mattn/vim-goimports"
    comment: "Handle imports on save"
  - name: "sebdah/vim-delve"
    comment: "Delve Go debugger"
  - name: "neovim/nvim-lspconfig"
    comment: ""
  - name: "hrsh7th/cmp-nvim-lsp"
    comment: ""
  - name: "hrsh7th/cmp-buffer"
    comment: ""
  - name: "hrsh7th/nvim-cmp"
    comment: ""
  - name: "hrsh7th/cmp-path"
    comment: ""
  - name: "hrsh7th/cmp-cmdline"
    comment: ""
  - name: "hrsh7th/vim-vsnip"
    comment: "Snippets feature for Neovim"
  - name: "hrsh7th/vim-vsnip-integ"
    comment: "Vsnip integration for Neovim plugins"
  - name: "junegunn/vim-easy-align"
    comment: "Easy alignment of code on symbols"
  - name: "tpope/vim-surround"
    comment: "Vim surround text objects"
  - name: "tpope/vim-commentary"
    comment: "Comment out code with motion"
  - name: "majutsushi/tagbar"
    comment: "Tagbar is a menubar with ctags"
  - name: "terryma/vim-multiple-cursors"
    comment: "Multiple cursors in Vim"
  - name: "unblevable/quick-scope"
    comment: "Quickly jump between characters"
  - name: "nvim-treesitter/nvim-treesitter"
    comment: "Treesitter"
  - name: "nvim-treesitter/nvim-treesitter-context"
    comment: "Treesitter context"
  - name: "nvim-lua/plenary.nvim"
    comment: "Plenary test framework"
  - name: "nvim-telescope/telescope.nvim"
    comment: "Telescope"
  - name: "ryanoasis/vim-devicons"
    comment: "Devicons"
  - name: "morhetz/gruvbox"
    comment: "Gruvbox color scheme"
