---
- name: Install Lf
  tags:
  - lf
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Lf with a package manager
    ansible.builtin.package:
      name:
      - lf
      state: latest

  - name: Ensure Lf configuration directory is present
    ansible.builtin.file:
      path: "{{ lf_config_dir }}"
      state: directory
      mode: u=+rwx,g=+r-wx,o=+r-wx

  - name: Ensure Lf configuration file is available
    ansible.builtin.copy:
      src: "files/lfrc"
      dest: "{{ lf_config_dir }}/lfrc"
      mode: u=+rw-x,g=+r-wx,o=+r-wx
...
