---
- name: Install Wget
  tags: wget
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Wget with a package manager
    ansible.builtin.package:
      name:
        - wget
      state: latest
...
