---
- name: Install Jq
  tags: jq
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Jq with a package manager
    ansible.builtin.package:
      name:
      - jq
      state: latest
...
