---
- name: Setup Go programming language
  tags:
  - go
  block:
  - name: Ensure Go configuration directory is present
    ansible.builtin.file:
      path: "{{ go_config_dir }}"
      state: directory
      mode: u=+rwx,g=+r-wx,o=+r-wx

  - name: Ensure Go file with environmental variables is available
    ansible.builtin.template:
      src: templates/goenv.j2
      dest: "{{ go_env_file_path }}"
      mode: u=+rwx,g=+r-wx,o=+r-wx

  - name: Ensure Go default directory is present
    ansible.builtin.file:
      path: "{{ go_default_dir }}"
      state: directory
      mode: u=+rwx,g=+r-wx,o=+r-wx

  - name: Ensure Go setup script is available
    ansible.builtin.template:
      src: templates/setup.j2
      dest: "{{ go_setup_script_file_path }}"
      mode: u=+rwx,g=+r-wx,o=+r-wx

  - name: Run Go setup script
    ansible.builtin.command: sh "{{ go_setup_script_file_path }}"
    register: setup_out
    changed_when: setup_out is search("Added new Go version")

  - debug:
      msg: "{{ setup_out }}"

  - name: Install Go programs
    ansible.builtin.command: "{{ ansible_env.HOME }}/.go/goroot/current/bin/go install {{ item }}"
    with_items: "{{ go_pkgs_to_install }}"
    when: go_pkgs_to_install is defined
    changed_when: false
    environment:
      GOPATH: "{{ go_gopath_env }}"
      GOROOT: "{{ go_goroot_env }}"
      GOBIN: "{{ go_gobin_env }}"
...
