---
- name: Install Htop
  tags: htop
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Htop with a package manager
    ansible.builtin.package:
      name:
      - htop
      state: latest
...
