---
- name: Install Firefox
  tags: firefox
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Firefox with a package manager
    ansible.builtin.package:
      name:
      - firefox
      state: latest
...
