---
- name: Install Node
  tags: node
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Node with a package manager
    ansible.builtin.package:
      name:
        - "{{ 'nodejs' if ansible_os_family == 'Debian' else 'node' }}"
      state: latest
...
