---
- name: Install Yq
  tags: yq
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Yq with a package manager
    ansible.builtin.package:
      name:
      - yq
      state: latest
...
