---
- name: Install Ripgrep
  tags:
  - ripgrep
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Ripgrep with a package manager
    ansible.builtin.package:
      name:
      - ripgrep
      state: latest
...
