---
- name: Install Git
  tags:
  - git
  - nvm
  - pyenv
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Git with a package manager
    ansible.builtin.package:
      name:
      - git
      state: latest

  - name: Ensure Git configuration file is available
    template:
      src: templates/gitconfig.j2
      dest: "{{ git_config_dir }}/.gitconfig"
      mode: u=+rw-x,g=+r-wx,o=+r-wx
...
