---
- name: Install Fzf
  tags: fzf
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Fzf with a package manager
    ansible.builtin.package:
      name:
        - fzf
      state: latest
...
