#!/bin/bash

# Compile LATEX file to PDF

set -eou pipefail

usage="Usage: comp FILE [-o]"
args_error="The max number of arguments is 2. You passed $#."
file_error="File does not exit!"
commands=(Rscript pdflatex biber makeglossaries)

# Checking if all programs are installed
for c in "${commands[@]}"; do
    type "$c" >/dev/null 2>&1 || {
        echo >&2 "I require $c but it's not installed. Aborting...";
        exit 1
    }
done

[[ "$#" -gt 2 ]] && printf "%s\n%s\n" "$args_error" "$usage" && exit 2
[[ "$#" -lt 1 ]] && printf "%s\n%s\n" "$args_error" "$usage" && exit 2
! [[ -f "$1.tex" ]] && printf "Error: %s\n\n%s\n" "$file_error" "$usage" && exit 3

trap "echo Terminated execution.' && exit 3" SIGTERM

if [[ "$#" -eq 1 ]]; then
# Biber takes the filename without the file extension and Knitr needs the RNW file
Rscript -e "library(knitr); require(reticulate); knit('$1.Rnw')" &&  pdflatex "$1" && biber "$1" && makeglossaries "$1" && pdflatex "$1"
elif [[ "$2" = "-o" ]]; then
    pdflatex "$1" && biber "$1" && makeglossaries "$1" && pdflatex "$1" 
else
    echo "Uncaught error!"
    echo "$usage" && exit 4
fi
