#!/bin/sh

# Function for converting TEX to DOCX with a reference list
[ $# -ne 2 ] && echo "Give TEX file as 1st argument and BIB as the 2nd." && exit

if [ -f "$1" ] && [ -f "$2" ]; then
    # Use pandoc to convert TEX file to DOCX
    pandoc -f latex -t docx --bibliography="$2" "$1" -o "${1%.*}.docx" --verbose -M reference-section-title=References ||
    exit 1
else
    echo "Both the TEX and BIB files have to exist!"
    exit 1
fi
