#!/bin/sh

# Open dir with PhD references in fzf and open the selected file
for n in $(find ~/Documents/_files/_research/monograph/phd_references -maxdepth 1 -type f -name "*.pdf" | fzf -m | sort -r)
do
    open "$n"
    sleep 0.6
done
