#!/bin/sh

# Switch between light and dark background in Alacritty.

config="$HOME/.dotfiles/alacritty.yml"

cur="$(grep -E '^colors' "$config")"

case "$cur" in
	*light) sed -iE "s/\*light/\*dark/g" "$config" ;;
	*dark)  sed -iE "s/\*dark/\*light/g" "$config" ;;
	*) printf "Check the \"colors\" paramter in %s\n" "$config"
esac

