---
- name: Install Goreleaser
  tags: goreleaser
  become_user: "{{ user }}"
  block:
    - name: Install Goreleaser on MacOS
      include_tasks: macos.yaml
      when: ansible_distribution == "MacOSX"
...
