---
- name: Install Goreleaser
  tags: goreleaser
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Add Goreleaser source file for the Apt package manager
    ansible.builtin.apt_repository:
      repo: "deb [trusted=yes] https://repo.goreleaser.com/apt/ /"
      state: present
    when: ansible_os_family == 'Debian'

  - name: Install Goreleaser with a package manager
    ansible.builtin.package:
      name:
        - goreleaser
      state: latest
...
