---
- name: Install Docker
  tags: docker
  block:
    - name: Install Docker on MacOS
      include_tasks: macos.yaml
      when: ansible_distribution == "MacOSX"

    - name: Install Docker on Debian-based OS with apt
      import_tasks: debian.yaml
      when: >
        ansible_distribution == "Debian" or
        ansible_distribution == "Ubuntu"
...
