---
- name: Install Shellcheck
  tags:
  - shellcheck
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Shellcheck with a package manager
    ansible.builtin.package:
      name:
      - shellcheck
      state: latest
...
