---
- name: Install Lynx
  tags: lynx
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Lynx with a package manager
    ansible.builtin.package:
      name:
        - lynx
      state: latest

  - name: Ensure Lynx configuration directory is present
    file:
      path: "{{ lynx_config_dir }}"
      state: directory
      mode: u=+rwx,g=+r-wx,o=+r-wx

  - name: Ensure Lynx configuration files are available
    copy:
      src: "files/{{ item }}"
      dest: "{{ lynx_config_dir }}/{{ item }}"
      mode: u=+rw-x,g=+r-wx,o=+r-wx
    with_items : "{{ lynx_config_files }}"
...
