#!/bin/sh
#
# Function that sets a color scheme matching the selected wallpaper

if [ $# -eq 0 ]; then
        # Select a wallpaper and pass it to fzf
        walpaper="$(find ~/../../Library/Desktop\ Pictures | fzf)"
        wal -i "$walpaper" 2> /dev/null
elif [ "$1" = "-r" ]; then
        # Reload the existing scheme
        wal -R
else
    echo "Usage: wp [-r]"
    exit 1
fi
