---
- name: Include custom shell executables
  tags: exec
  become: true
  block:
    - name: Copy custom executables to the target bin directory
      copy:
        src: "{{ item }}"
        dest: "{{ dest_dir }}"
        mode: u=+rwx,g=+rx-w,o=+rx-w
        owner: "{{ lookup('ansible.builtin.env', 'USER', default=Undefined) }}"
      loop: "{{ query('fileglob', 'files/*') }}"
...
