---
- name: Install Entr
  tags:
  - entr
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Entr with a package manager
    ansible.builtin.package:
      name:
      - entr
      state: latest
...
