---
- name: Install Gh
  tags: gh
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Gh with a package manager
    ansible.builtin.package:
      name:
        - gh
      state: latest

  - name: Ensure that Gh configuration directory is present
    file:
      path: "{{ gh_config_dir }}"
      state: directory
      mode: u=+rwx,g=+r-wx,o=+r-wx

  - name: Ensure that Gh config file is available
    copy:
      src: files/config.yml
      dest: "{{ gh_config_dir }}/config.yml"
      mode: u=+rw-x,g=+r-wx,o=+r-wx

  - name: Ensure Gh hosts file is available
    template:
      src: templates/hosts.yml.j2
      dest: "{{ gh_config_dir }}/hosts.yml"
      mode: u=+rw-x,g=+r-wx,o=+r-wx
...
