---
- name: Install Fd
  tags: fd
  become: "{{ should_run_pkg_mgr_as_root }}"
  block:
  - name: Install Fd with a package manager
    ansible.builtin.package:
      name:
        # This is a hack. The package is named 'fd-find' on Debian-based
        # distros. On *most* other distros it's 'fd', but on Fedora it's also
        # 'fd-find'. I am not planning to play around with Fedora. Check the
        # README file in case the task fails.
        - "{{ 'fd-find' if ansible_os_family == 'Debian' else 'fd' }}"
      state: latest

  - name: Link Fdfind on Debian-based distributions to Fd
    file:
      src: /usr/bin/fdfind
      dest: /usr/local/bin/fd
      state: link
    when: ansible_os_family == 'Debian'
...
